// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/porotikovaverk99-pixel/gophkeeper/internal/handler (interfaces: KeeperService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_keeper_service.go -package=mocks github.com/porotikovaverk99-pixel/gophkeeper/internal/handler KeeperService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/porotikovaverk99-pixel/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockKeeperService is a mock of KeeperService interface.
type MockKeeperService struct {
	ctrl     *gomock.Controller
	recorder *MockKeeperServiceMockRecorder
	isgomock struct{}
}

// MockKeeperServiceMockRecorder is the mock recorder for MockKeeperService.
type MockKeeperServiceMockRecorder struct {
	mock *MockKeeperService
}

// NewMockKeeperService creates a new mock instance.
func NewMockKeeperService(ctrl *gomock.Controller) *MockKeeperService {
	mock := &MockKeeperService{ctrl: ctrl}
	mock.recorder = &MockKeeperServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeeperService) EXPECT() *MockKeeperServiceMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method.
func (m *MockKeeperService) CreateEntry(ctx context.Context, userID uuid.UUID, entry *model.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntry", ctx, userID, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEntry indicates an expected call of CreateEntry.
func (mr *MockKeeperServiceMockRecorder) CreateEntry(ctx, userID, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockKeeperService)(nil).CreateEntry), ctx, userID, entry)
}

// DeleteEntry mocks base method.
func (m *MockKeeperService) DeleteEntry(ctx context.Context, userID, entryID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntry", ctx, userID, entryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry.
func (mr *MockKeeperServiceMockRecorder) DeleteEntry(ctx, userID, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockKeeperService)(nil).DeleteEntry), ctx, userID, entryID)
}

// GetEntry mocks base method.
func (m *MockKeeperService) GetEntry(ctx context.Context, userID, entryID uuid.UUID) (*model.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", ctx, userID, entryID)
	ret0, _ := ret[0].(*model.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockKeeperServiceMockRecorder) GetEntry(ctx, userID, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockKeeperService)(nil).GetEntry), ctx, userID, entryID)
}

// Login mocks base method.
func (m *MockKeeperService) Login(ctx context.Context, login, password string) (string, *model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockKeeperServiceMockRecorder) Login(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockKeeperService)(nil).Login), ctx, login, password)
}

// Ping mocks base method.
func (m *MockKeeperService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockKeeperServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockKeeperService)(nil).Ping), ctx)
}

// Register mocks base method.
func (m *MockKeeperService) Register(ctx context.Context, login, password string) (string, *model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Register indicates an expected call of Register.
func (mr *MockKeeperServiceMockRecorder) Register(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockKeeperService)(nil).Register), ctx, login, password)
}

// SyncEntries mocks base method.
func (m *MockKeeperService) SyncEntries(ctx context.Context, userID uuid.UUID, since time.Time) ([]model.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncEntries", ctx, userID, since)
	ret0, _ := ret[0].([]model.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncEntries indicates an expected call of SyncEntries.
func (mr *MockKeeperServiceMockRecorder) SyncEntries(ctx, userID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncEntries", reflect.TypeOf((*MockKeeperService)(nil).SyncEntries), ctx, userID, since)
}

// UpdateEntry mocks base method.
func (m *MockKeeperService) UpdateEntry(ctx context.Context, userID uuid.UUID, entry *model.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntry", ctx, userID, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntry indicates an expected call of UpdateEntry.
func (mr *MockKeeperServiceMockRecorder) UpdateEntry(ctx, userID, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockKeeperService)(nil).UpdateEntry), ctx, userID, entry)
}
